---
title: "Quarto Customization"
format: html
execute: 
  warning: false
---

Suppressing warnings and messages just for this code chunk.

```{r}
#| warning: false
#| message: false
library(tidyverse)
```

Running code, but not showing output.

```{r}
#| include: false
#return first 6 lines of starwars data

head(starwars)

#return dimensions of the starwars data
dim(starwars)
```

Showing output, but not code.

```{r}

#| warning: false 
#| include: false
ggplot(data = starwars, aes(x = height, y = mass, color = mass))+ 
  geom_point()+ 
  labs( x = "Height (cm)", 
        y = "Mass (g)")
          
```

```{r}
#| warning: false
#| fig-cap: "caption text"
#| fig-alt: "figure alt text"
ggplot(data = starwars, aes(x = height)) + 
  geom_histogram(color = "red", fill = "purple")
```

Find summary stats for Star Wars characters

```{r}
# remove NAs from data

sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_median <- median(starwars$height, na.rm = TRUE)
sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_sd <- sd(starwars$height, na.rm = TRUE)

```

The mean height of the characters in Starwars is `r round(sw_height_mean, 1)` centimeters.
